/*const Discord = require("discord.js");
const figlet = require("figlet")
module.exports.run = async (bot, message, args) => {
     

  message.react("✅");
  if(args.join(' ').length > 14) return message.channel.send('Only 14 characters are admitted!') 
  if (!args.join(' ')) return message.channel.send('Please, provide text to format in ASCII! Usage: ascii <text>')
    figlet(args.join(' '), (err, data) => {
      message.channel.send('```' + data + '```')
    })
};

*/
const Discord = require("discord.js");
const asciify = require(`asciify`)
module.exports.run = async (client, message, args) => {
    const fonts = [
			`3-d`,
			`3x5`,
			`5lineoblique`,
			`acrobatic`,
			`alligator`,
			`alligator2`,
			`alphabet`,
			`avatar`,
			`banner`,
			`banner3-D`,
			`banner3`,
			`banner4`,
			`barbwire`,
			`basic`,
			`bell`,
			`big`,
			`bigchief`,
			`binary`,
			`block`,
			`bubble`,
			`bulbhead`,
			`calgphy2`,
			`caligraphy`,
			`catwalk`,
			`chunky`,
			`coinstak`,
			`colossal`,
			`computer`,
			`contessa`,
			`contrast`,
			`cosmic`,
			`cosmike`,
			`cricket`,
			`cursive`,
			`cyberlarge`,
			`cybermedium`,
			`cybersmall`,
			`diamond`,
			`digital`,
			`doh`,
			`doom`,
			`dotmatrix`,
			`drpepper`,
			`eftichess`,
			`eftifont`,
			`eftipiti`,
			`eftirobot`,
			`eftitalic`,
			`eftiwall`,
			`eftiwater`,
			`epic`,
			`fender`,
			`fourtops`,
			`fuzzy`,
			`goofy`,
			`gothic`,
			`graffiti`,
			`hollywood`,
			`invita`,
			`isometric1`,
			`isometric2`,
			`isometric3`,
			`isometric4`,
			`italic`,
			`ivrit`,
			`jazmine`,
			`jerusalem`,
			`katakana`,
			`kban`,
			`larry3d`,
			`lcd`,
			`lean`,
			`letters`,
			`linux`,
			`lockergnome`,
			`madrid`,
			`marquee`,
			`maxfour`,
			`mike`,
			`mini`,
			`mirror`,
			`mnemonic`,
			`morse`,
			`moscow`,
			`nancyj-fancy`,
			`nancyj-underlined`,
			`nancyj`,
			`nipples`,
			`ntgreek`,
			`o8`,
			`ogre`,
			`pawp`,
			`peaks`,
			`pebbles`,
			`pepper`,
			`poison`,
			`puffy`,
			`pyramid`,
			`relief`,
			`relief2`,
			`rev`,
			`roman`,
			`rot13`,
			`rounded`,
			`rowancap`,
			`rozzo`,
			`runic`,
			`runyc`,
			`sblood`,
			`script`,
			`serifcap`,
			`shadow`,
			`short`,
			`slant`,
			`slide`,
			`slscript`,
			`small`,
			`smisome1`,
			`smkeyboard`,
			`smscript`,
			`smshadow`,
			`smslant`,
			`smtengwar`,
			`speed`,
			`stampatello`,
			`standard`,
			`starwars`,
			`stellar`,
			`stop`,
			`straight`,
			`tanja`,
			`tengwar`,
			`term`,
			`thick`,
			`thin`,
			`threepoint`,
			`ticks`,
			`ticksslant`,
			`tinker-toy`,
			`tombstone`,
			`trek`,
			`tsalagi`,
			`twopoint`,
			`univers`,
			`usaflag`,
			`wavy`,
			`weird`
		]

		const font = args.shift()

		if (!fonts.includes(font)) return message.channel.send(`Use \` d!ascii (font) (text)\`\n\`${font}\` is not in the list, you can look which fonts the bot have use this command: //ascii-font`)

		asciify(args.join(` `), font, (error, response) => {
			if (error) return message.channel.send(error, { code: true })
			message.channel.send(response, { code: true })
		})
		return true
}

module.exports.help = {
    name: "ascii"
}
